bugreports/views.py, exec/templates/exec/index.html, forum/templates/forum/forum.html, forum/templates/forum/response.html, forum/templates/forum/thread.html, rpgs/models.py, rpgs/templates/rpgs/detail.html, tgrsite/templates/tgrsite/main.html, users/templates/users/view.html
Additionally add character limit to an rpg's desc
=> Improve handling of long text by wrapping and truncating; Restrict access to bug reports

requirements.txt, users/templates/users/login.html, users/templates/users/signup.html, users/views.py
environment variable `GCAPTCHA_SECRET` is now required. Get a reCaptcha secret (and site key) from https://www.google.com/recaptcha/admin.
=> implement recaptcha.

exec/templates/exec/index.html, users/forms.py, users/models.py, users/templates/users/edit.html
As it says on the tin. :diamond_shape_with_a_dot_inside:
=> Exec Photos added. Not sure if more work needed.

forum/models.py, forum/views.py, messaging/models.py, messaging/views.py, newsletters/views.py, notifications/admin.py, notifications/apps.py, notifications/models.py, notifications/templates/notifications/index.html, notifications/tests.py, notifications/urls.py, notifications/views.py, rpgs/views.py, tgrsite/settings.py, tgrsite/templates/tgrsite/addnavbar.html, tgrsite/urls.py, users/models.py
=> Notifications!

newsletters/templates/newsletters/detail.html, newsletters/templates/newsletters/email-version.html
This feels a tiny bit dangerous, but it'll be okay.
=> Newsletters can now contain HTML. BE CAREFUL COMMS OFFICERS

forum/models.py
I think this fixes it, but I'd like someone that knows more Django to check I'm not about to break something horribly with this. (looks at Ash)
=> Fixed loss of formatting bug (#101)

users/models.py
=> Fix new line stripping in admin site

bugreports/views.py, forum/views.py, newsletters/models.py, newsletters/templates/newsletters/detail.html, newsletters/templates/newsletters/email-version.html, newsletters/templates/newsletters/plain-email-version.txt, newsletters/templatetags/markout_tags.py, newsletters/urls.py, newsletters/views.py, notifications/admin.py, notifications/forms.py, notifications/models.py, notifications/tasks.py, notifications/templates/notifications/index.html, notifications/templates/notifications/plain-summary-email.txt, notifications/templates/notifications/preferences.html, notifications/templates/notifications/summary-email.html, notifications/urls.py, notifications/views.py, rpgs/views.py, tgrsite/settings.py, tgrsite/templates/tgrsite/addnavbar.html, tgrsite/templates/tgrsite/basecontent.html, tgrsite/templates/tgrsite/emailcontent.html, tgrsite/templates/tgrsite/main.html, users/models.py, users/templates/users/edit.html, users/templates/users/view.html, users/views.py
Add email notifications to notifications. This includes email settings as well as a few new kinds of notifications
=> Emailnotifications

notifications/forms.py, notifications/models.py
=> Fixed notification bugs

statics/templates/statics/webcal.html, tgrsite/context_processors.py, tgrsite/settings.py, tgrsite/templates/admin/base.html, tgrsite/templates/tgrsite/addnavbar.html, tgrsite/templates/tgrsite/basecontent.html, timetable/templates/timetable/timetable.html
=> Small bug fixes

inventory/templates/inventory/record_detail.html, inventory/views.py
Unauthenticated users could edit inventory records. They shouldn't.
=> Fix permission bug in inventory

tgrsite/templates/tgrsite/addnavbar.html
SU link broken by SU without any forwarding... :/
=> Fix SU link

tgrsite/templates/parts/pagination.html, timetable/admin.py, timetable/models.py, timetable/templates/timetable/parts/render_timetable.html, timetable/templatetags/timetable_tags.py, timetable/views.py, users/admin.py
A feature and a bug fix. Fixes a bug I thought I had already fixed but then broke again (we really need some regression testing...)
Adds the ability to add links to the schedule for rooms to link to the interactive map
=> Bug fixes and adding links to schedule to rooms search

inventory/forms.py, inventory/templates/inventory/record_detail.html, messaging/forms.py, messaging/views.py, navbar/templates/nav.html, rpgs/templates/rpgs/index.html, rpgs/urls.py, rpgs/views.py, tgrsite/templates/parts/render_member.html, tgrsite/templates/parts/tag_typeahead.html, tgrsite/templates/tgrsite/basecontent.html, tgrsite/templates/tgrsite/main.html, timetable/templatetags/timetable_tags.py, users/captcha.py, users/templates/registration/password_reset_email.html
Also includes more filters for events
=> Fix 500 error on password reset

rpgs/templates/rpgs/parts/event.html
=> Login hint on events

minutes/templates/minutes/edit.html, minutes/views.py, rpgs/templates/rpgs/index.html, rpgs/views.py
Fix permissions for meeting adding being wrong
Change sorting of events to put full events last
Change filtering of events to default to display full
=> Events Hiding change, and perms fix

inventory/admin.py, minutes/admin.py, navbar/admin.py, static_resources/markdown-editor.js, users/forms.py, users/templates/users/edit.html
had the wrong branch checked out when committing these... Oops.
=> Changes meant to be in master

gallery/views.py, messaging/templates/messaging/parts/messages.html, users/forms.py, users/models.py, users/templates/users/view.html
First appearance of pronoun input. Also contains newsletter subject fix.
=> New pronoun support

forum/models.py, forum/templates/forum/parts/thread_list.html, forum/templates/forum/thread.html, forum/urls.py, forum/views.py, messaging/views.py, minutes/views.py, pages/admin.py, pages/models.py, pages/templates/pages/page.html, pages/templates/pages/parts/sidebar_widget.html, rpgs/templates/rpgs/parts/event.html, rpgs/views.py, templatetags/management/commands/forum_migrate.py, timetable/admin.py, timetable/models.py, timetable/templates/timetable/parts/widgets/event_widget.html, timetable/templates/timetable/parts/widgets/poster_widget.html, timetable/templates/timetable/timetable.html, timetable/templatetags/event_tags.py, users/views.py
Slightly smaller than I'd planned, but I took on more than I expected with my project, and coursework takes precedence.
Contains following changes:
* Fixes a redirect bug in timetable admin and ordering for ease
* Hides profile pages from anon users
* Adds the name of the group chat to the notifications, and separates forum subscriptions from having * participated.
* Allows forum threads to be locked
* Adds framework for dynamic 'widgets' in static pages
* Adds model for special events
* Adds widgets for special events on the front page
* Automates the upcoming events panel
* Formalises the experiment with the event poster in the side bar
=> Winter changes

rpgs/templates/rpgs/parts/event.html
=> Fix img flowing out of events

rpgs/templates/rpgs/parts/event.html, timetable/models.py
=> Tiny tweaks

forum/views.py
=> Make response notifications link straight to the thread response

exec/models.py
Co-Op Officer wouldn't fit! Add more space.
=> Update Exec Models

minutes/forms.py
=> Revert "Allow admin preview in minutes as well"

newsletters/urls.py, newsletters/views.py
The email-version button on the newsletter page should also use premailer to check it hasn't ducked up
=> Make email version of newsletter also use premailer

pages/admin.py, timetable/admin.py, users/admin.py, users/models.py
=> Some admin tweaks.

rpgs/forms.py, rpgs/models.py, rpgs/views.py, tgrsite/templates/test.html, tgrsite/templates/test_old.html
=> Add Finishes field to events.

inventory/forms.py, inventory/models.py, inventory/templates/inventory/all_inventory.html, inventory/templates/inventory/all_loans.html, inventory/templates/inventory/all_suggestions.html, inventory/templates/inventory/edit_loan.html, inventory/templates/inventory/edit_record.html, inventory/templates/inventory/edit_suggestion.html, inventory/templates/inventory/loan_detail.html, inventory/templates/inventory/record_detail.html, inventory/templates/inventory/suggestion_detail.html
This adds some more QoL fixes to loans. The loan availability check is now correct, invalid dates are handled correctly, and optional verbose names for inventories so that spaces can make a return
=> More loan refinements

inventory/forms.py, inventory/models.py, inventory/templates/inventory/all_loans.html, inventory/templates/inventory/loan_detail.html, inventory/urls.py, inventory/views.py, inventory/views_api.py, manage.py, notifications/forms.py, notifications/models.py, redirect/admin.py, redirect/models.py, redirect/views.py, rpgs/views.py, tgrsite/settings.py, tgrsite/urls.py, tgrsite/utils.py, users/permissions.py
Fixes permissions bugs. Introduces new system to prevent that from being a future problem. Includes notifications for loan events to make life easier for both users and administrators
=> Much more refinements for the loans system

exec/forms.py, exec/models.py, exec/templates/exec/index.html, exec/views.py, templatetags/templates/markdown_preview_text.html, templatetags/urls.py, templatetags/views.py
Also allows markdown formatting in the bios
=> Add responsibilities to the exec page. 

rpgs/views.py, tgrsite/templates/parts/render_member.html
And I claim that I don't test on prod...
=> Yet more hotfixes

rpgs/views.py
Gods, this has been a disaster...
=> Doh. Stupid Stupid Stupid

rpgs/__init__.py, rpgs/admin.py, rpgs/apps.py, rpgs/models.py, users/admin.py
Also renamed rpgs to Events in admin panel to reflect website presentation
=> Improve adding multiple people to rpg as dms.

assets/admin.py, assets/models.py, assets/templatetags/assets.py, users/admin.py, users/models.py, users/templates/users/achievements.html
=> Allow achievements to change image based on darkmode

users/models.py, users/views.py
This decides whether an achievement counts or not
=> Added achievement fairness

users/admin.py
=> Fix users search, and anon redirect acheiv bugs

votes/forms.py, votes/templates/votes/ticket.html, votes/urls.py, votes/views.py
=> Add more ticket issuing algorithms.

rpgs/models.py, timetable/models.py
=> Character limit increases

users/management/commands/deadname_removal.py
Let deadname removal autodetect terminals that don't support colours
=> No colour autodetect

static_resources/markdown-editor.js
This has been bugging me for over a year, and I've found it.
=> Fix an *old* bug of mine

pages/templates/pages/page.html
=> No breadcrumbs, but template only

notifications/models.py, users/forms.py, users/views.py
A prototype for adding sign-up notification options.
=> First draft at addressing #318

votes/admin.py, votes/models.py, votes/stv.py, votes/templates/votes/parts/table.html, votes/templates/votes/stv_results.html, votes/templatetags/vote_tags.py, votes/views.py
Add machine readable logging into the STV calculator, and redesign the stv results page so that it generates a html table for the voting summary, to simplify administration of elections. This would probably finally close #321.
=> Vote table

tgrsite/templates/parts/pagination.html
Fixes #337. Alternative to #339 
Wide: 
Narrow:
=> Update pagination to truncate when very long

minutes/templates/minutes/parts/widgets/latest_widget.html, minutes/templatetags/meeting_tags.py, newsletters/templates/newsletters/parts/widgets/latest_widget.html, newsletters/templatetags/newsletter_tags.py, pages/models.py, pages/templates/pages/parts/sidebar_widget.html, rpgs/templates/rpgs/index.html, rpgs/templates/rpgs/parts/event.html
Closes #312 
Currently looks like 
Can change as desired
=> Add new widgets for latest newsletter and latest meeting minutes

rpgs/templates/rpgs/parts/event.html
Fixing internal server error on events page
=> Fixing internal server error on events page

navbar/models.py
I need one more character for a drop down item I need to add.
=> Increasing length of drop down text by 1
